server:
  port: 8080
spring:
  application:
    name: agendamento-api
  data:
    mongodb:
      host: mongo
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: agendamento
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    admin:
      client-id: admin

management:
  tracing:
    sampling:
      probability: 1
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    enable:
      jvm: true
    export:
      prometheus:
        enabled: true
    tags:
      application: agendamento-api
    distribution:
      slo:
        http: '5ms,10ms,25ms,50ms,100ms,200ms,300ms,400ms,500ms,1s,2s'
      percentiles-histogram:
        http:
          server:
            requests: true
