name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Comando LS
        run: ls -l
      - name: Docker build chatservice
        run: echo "Docker Build chatServices"
      - name: Docker build api
        run: echo "Docker Build api"   
      
